sudo: required
language: generic

services: 
  - docker 
    
before_install:
  - docker build -t jrbe228/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true jrbe228/docker-react npm run test 
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-012256633746"
  bucket_path: "docker-react2"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"